### ISSUE TITLE
hi can i make everything redirect to the new site please thanks ly all <3 from your favourite little kitten rosie

### ISSUE THREAD

**Issue by jqms** [ocwebsite/ocwebsite.github.io#24]
hi can i make everything redirect to the new site please thanks ly all <3 from your favourite little kitten rosie

**Comment by Vitsowdy** [comment]
2f022fd066988d364afff3ebdb1bba30a9fc594c hehehaha

**Comment by jqms** [comment]
i wanted to do it properly so the old links didnt get killed man..

**Comment by Vitsowdy** [comment]
Urgh fine

**Comment by jqms** [comment]
lol

**Comment by jqms** [comment]
thahnk you vit u awesome
